#!/bin/bash

echo "ipv6router-utils Post install shell script"

default_conf_folder="/opt/ipv6router-utils/default-conf"
upgrade_folder="/opt/ipv6router-utils/upgrade"

ut_default_conf_folder="../opt/ipv6router-utils/default-conf"

overwrite_or_create_file_to()
{
    FILE=$1
    DESTINATION=$2

    if [ -f "$FILE" ]
    then
        if [ -f "$DESTINATION" ]
        then
            echo "Overwriting $DESTINATION by $FILE"       
        else
            echo "Creating $DESTINATION from $FILE"
        fi    
        cat $FILE > $DESTINATION
    else
        echo "File not found : $FILE"
    fi
}


apply_configuration_from()
{
    SOURCE_FOLDER=$1

    echo "Applying configuration from $SOURCE_FOLDER"

    overwrite_or_create_file_to "$SOURCE_FOLDER/etc/dhcpcd.conf" "/etc/dhcpcd.conf"
    overwrite_or_create_file_to "$SOURCE_FOLDER/etc/radvd.conf" "/etc/radvd.conf"
    overwrite_or_create_file_to "$SOURCE_FOLDER/etc/tayga.conf" "/etc/tayga.conf"
    overwrite_or_create_file_to "$SOURCE_FOLDER/etc/default/tayga" "/etc/default/tayga"
    overwrite_or_create_file_to "$SOURCE_FOLDER/etc/bind/named.conf.options" "/etc/bind/named.conf.options"
    overwrite_or_create_file_to "$SOURCE_FOLDER/etc/wide-dhcpv6/dhcp6s.conf" "/etc/wide-dhcpv6/dhcp6s.conf"

    #copy_file_to_if_exists "/etc/sysctl.conf" "$DESTINATION_FOLDER/etc"
    #copy_file_to_if_exists "/etc/iptables.ipv4.nat" "$DESTINATION_FOLDER/etc"
    #copy_file_to_if_exists "/etc/rc.local" "$DESTINATION_FOLDER/etc"

    echo "Done Applying configuration"
}



case "$1" in
    configure)

	if [ -d "$upgrade_folder" ]
	then
		echo "Upgrade ongoing"
        echo "Done"
	fi
        echo "First Installation, applying default configuration"
        apply_configuration_from $default_conf_folder      

        echo "Enabling ip forwarding"
        echo 1 > /proc/sys/net/ipv4/ip_forward
        echo 1 > /proc/sys/net/ipv6/conf/all/forwarding

        echo "Making it permanent"
        sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf

        echo "Enabling NAT44 on eth0"
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

        echo "Saving Rules for auto enabling at startup"
        iptables-save > /etc/iptables.ipv4.nat 
        sed -i -e '$i \iptables-restore < /etc/iptables.ipv4.nat\n' /etc/rc.local

        echo "Installation Done! Please reboot using : sudo reboot"
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
    ;;
esac

exit 0
